const attributes = [
  { id: 1, name: "Color" },
  { id: 2, name: "Tamaño" },
  { id: 3, name: "Peso" },
  { id: 4, name: "Material" },
  { id: 5, name: "Marca" },
  { id: 6, name: "Modelo" },
  { id: 7, name: "Garantía" },
  { id: 8, name: "Fabricante" },
  { id: 9, name: "Origen" },
  { id: 10, name: "Consumo energético" },
  { id: 11, name: "Resolución" },
  { id: 12, name: "Duración batería" },
  { id: 13, name: "Tipo de conexión" },
  { id: 14, name: "Compatibilidad" },
  { id: 15, name: "Capacidad" },
  { id: 16, name: "Frecuencia" },
  { id: 17, name: "Voltaje" },
  { id: 18, name: "Resistencia al agua" },
  { id: 19, name: "Temperatura máxima" },
  { id: 20, name: "Color secundario" }
];

const productAttributes = [
  { product_id: 1, attribute_id: 1, value: "Rojo" },
  { product_id: 1, attribute_id: 2, value: "Mediano" },
  { product_id: 1, attribute_id: 3, value: "1.2 kg" },
  { product_id: 1, attribute_id: 4, value: "Plástico" },
  { product_id: 2, attribute_id: 1, value: "Negro" },
  { product_id: 2, attribute_id: 2, value: "Grande" },
  { product_id: 2, attribute_id: 5, value: "Sony" },
  { product_id: 2, attribute_id: 6, value: "ZX100" },
  { product_id: 2, attribute_id: 12, value: "8 horas" },
  { product_id: 3, attribute_id: 1, value: "Azul" },
  { product_id: 3, attribute_id: 4, value: "Aluminio" },
  { product_id: 3, attribute_id: 11, value: "1080p" },
  { product_id: 3, attribute_id: 10, value: "A+" },
  { product_id: 3, attribute_id: 19, value: "120 °C" },
  { product_id: 4, attribute_id: 1, value: "Verde" },
  { product_id: 4, attribute_id: 2, value: "Pequeño" },
  { product_id: 4, attribute_id: 13, value: "Bluetooth 5.0" },
  { product_id: 4, attribute_id: 18, value: "IP68" },
  { product_id: 5, attribute_id: 1, value: "Blanco" },
  { product_id: 5, attribute_id: 15, value: "256 GB" }
];